platform :ios, '7.0'

pod 'ReactiveCocoa'
pod 'NSDate+Calendar'

# Add Kiwi as an exclusive dependency for the App Tests target
target :EverydayReactiveCocoaTests, :exclusive => true do

pod 'Specta'
pod 'Expecta'

end
